webtalk_init -webtalk_dir C:/Users/Microapple/OneDrive - Rain/NSCSCC/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/Sim1_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 31 14:57:12 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "05bfb806-e998-4ed5-a98a-88ce0aad184f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "dab95d2888f043f1ae31caa2f70fdc71" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "194" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 5900X 12-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3700 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.23_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "21620_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1996346956 -regid "" -xml C:/Users/Microapple/OneDrive - Rain/NSCSCC/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/Sim1_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Microapple/OneDrive - Rain/NSCSCC/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/Sim1_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Microapple/OneDrive - Rain/NSCSCC/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/Sim1_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
