# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# IP: ip/DM/DM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DM || ORIG_REF_NAME==DM} -quiet] -quiet

# IP: ip/IM/IM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IM || ORIG_REF_NAME==IM} -quiet] -quiet

# XDC: c:/Users/Microapple/OneDrive - Rain/NSCSCC/project_1/project_1.gen/sources_1/ip/DM/DM_ooc.xdc

# XDC: c:/Users/Microapple/OneDrive - Rain/NSCSCC/project_1/project_1.gen/sources_1/ip/IM/IM_ooc.xdc
