#时钟信号连接
set_property PACKAGE_PIN AC19 [get_ports CLK100M]

#脉冲开关，用于输入作为复位信号，低电平有效
set_property PACKAGE_PIN Y3 [get_ports RST]

#脉冲开关，用于输入作为单步执行的clk
set_property PACKAGE_PIN Y5 [get_ports CLK]

set_property IOSTANDARD LVCMOS33 [get_ports CLK100M]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]

set_property PACKAGE_PIN D3 [get_ports {AN[7]}]
set_property PACKAGE_PIN D25 [get_ports {AN[6]}]
set_property PACKAGE_PIN D26 [get_ports {AN[5]}]
set_property PACKAGE_PIN E25 [get_ports {AN[4]}]
set_property PACKAGE_PIN E26 [get_ports {AN[3]}]
set_property PACKAGE_PIN G25 [get_ports {AN[2]}]
set_property PACKAGE_PIN G26 [get_ports {AN[1]}]
set_property PACKAGE_PIN H26 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]

set_property PACKAGE_PIN A2 [get_ports {Seg[7]}]
set_property PACKAGE_PIN D4 [get_ports {Seg[6]}]
set_property PACKAGE_PIN E5 [get_ports {Seg[5]}]
set_property PACKAGE_PIN B4 [get_ports {Seg[4]}]
set_property PACKAGE_PIN B2 [get_ports {Seg[3]}]
set_property PACKAGE_PIN E6 [get_ports {Seg[2]}]
set_property PACKAGE_PIN C3 [get_ports {Seg[1]}]
set_property PACKAGE_PIN C4 [get_ports {Seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seg[0]}]