# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Fxil/Desktop/nscscc2021_group_qualifier_submission-rc1/release_project/func_test_v0.01/cpu132_gettrace/rtl/xilinx_ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fxil/Desktop/nscscc2021_group_qualifier_submission-rc1/release_project/func_test_v0.01/cpu132_gettrace/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Fxil/Desktop/nscscc2021_group_qualifier_submission-rc1/release_project/func_test_v0.01/cpu132_gettrace/rtl/xilinx_ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fxil/Desktop/nscscc2021_group_qualifier_submission-rc1/release_project/func_test_v0.01/cpu132_gettrace/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
