# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Microapple/Desktop/release_project/func_test_v0.01/soc_sram_func/run_vivado/soc_lite.xdc

# IP: ip/divu/divu.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divu || ORIG_REF_NAME==divu} -quiet] -quiet

# IP: ip/div/div.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div || ORIG_REF_NAME==div} -quiet] -quiet
