# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Fxil/Desktop/vivadopro/MDU/MDU.srcs/sources_1/ip/divu/divu.xci
# IP: The module: 'divu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fxil/Desktop/vivadopro/MDU/MDU.gen/sources_1/ip/divu/divu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divu'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Fxil/Desktop/vivadopro/MDU/MDU.srcs/sources_1/ip/divu/divu.xci
# IP: The module: 'divu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fxil/Desktop/vivadopro/MDU/MDU.gen/sources_1/ip/divu/divu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divu'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
