# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Fxil/Desktop/nscscc2021_group_qualifier_submission-rc1/release_project/func_test_v0.01/soc_axi_func/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/div/div.xci
# IP: The module: 'div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fxil/Desktop/nscscc2021_group_qualifier_submission-rc1/release_project/func_test_v0.01/soc_axi_func/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/div/div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Fxil/Desktop/nscscc2021_group_qualifier_submission-rc1/release_project/func_test_v0.01/soc_axi_func/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/div/div.xci
# IP: The module: 'div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fxil/Desktop/nscscc2021_group_qualifier_submission-rc1/release_project/func_test_v0.01/soc_axi_func/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/div/div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
