# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Fxil/Desktop/vivadopro/MDU/MDU.srcs/sources_1/ip/div/div.xci
# IP: The module: 'div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fxil/Desktop/vivadopro/MDU/MDU.gen/sources_1/ip/div/div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Fxil/Desktop/vivadopro/MDU/MDU.srcs/sources_1/ip/div/div.xci
# IP: The module: 'div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fxil/Desktop/vivadopro/MDU/MDU.gen/sources_1/ip/div/div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
